# See https://github.com/golangci/golangci-lint#config-file
version: "2"

run:
  timeout: 10m
  issues-exit-code: 1

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: main

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - nolintlint
    - paralleltest
    - revive
    - staticcheck
