inpackage: False
with-expecter: True
disable-version-string: True
resolve-type-alias: False
issue-845-fix: True
log-level: "warn"
packages:
  github.com/luukvdm/mediator:
    config:
        dir: "mocks/{{.InterfaceDirRelative}}"
        outpkg: "mocks"
    interfaces:
      NotificationHandler:
      Request:
      Behavior:

