// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNotificationHandler is an autogenerated mock type for the NotificationHandler type
type MockNotificationHandler[T interface{}] struct {
	mock.Mock
}

type MockNotificationHandler_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockNotificationHandler[T]) EXPECT() *MockNotificationHandler_Expecter[T] {
	return &MockNotificationHandler_Expecter[T]{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, event
func (_m *MockNotificationHandler[T]) Handle(ctx context.Context, event T) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockNotificationHandler_Handle_Call[T interface{}] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - event T
func (_e *MockNotificationHandler_Expecter[T]) Handle(ctx interface{}, event interface{}) *MockNotificationHandler_Handle_Call[T] {
	return &MockNotificationHandler_Handle_Call[T]{Call: _e.mock.On("Handle", ctx, event)}
}

func (_c *MockNotificationHandler_Handle_Call[T]) Run(run func(ctx context.Context, event T)) *MockNotificationHandler_Handle_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockNotificationHandler_Handle_Call[T]) Return(_a0 error) *MockNotificationHandler_Handle_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationHandler_Handle_Call[T]) RunAndReturn(run func(context.Context, T) error) *MockNotificationHandler_Handle_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationHandler creates a new instance of MockNotificationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationHandler[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationHandler[T] {
	mock := &MockNotificationHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
