// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRequest is an autogenerated mock type for the Request type
type MockRequest[T interface{}] struct {
	mock.Mock
}

type MockRequest_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockRequest[T]) EXPECT() *MockRequest_Expecter[T] {
	return &MockRequest_Expecter[T]{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx
func (_m *MockRequest[T]) Handle(ctx context.Context) (T, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (T, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) T); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(T)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequest_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockRequest_Handle_Call[T interface{}] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRequest_Expecter[T]) Handle(ctx interface{}) *MockRequest_Handle_Call[T] {
	return &MockRequest_Handle_Call[T]{Call: _e.mock.On("Handle", ctx)}
}

func (_c *MockRequest_Handle_Call[T]) Run(run func(ctx context.Context)) *MockRequest_Handle_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRequest_Handle_Call[T]) Return(_a0 T, _a1 error) *MockRequest_Handle_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequest_Handle_Call[T]) RunAndReturn(run func(context.Context) (T, error)) *MockRequest_Handle_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockRequest creates a new instance of MockRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequest[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequest[T] {
	mock := &MockRequest[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
